name: Build Resume

on:
  push:
    paths:
      - 'resume.json'
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - run: npm install
    - run: npx playwright install chromium

    - run: npm run export-html

    - name: Prepare html for export PDF
      run: |
        sed -i 's/margin: 10mm 25mm;/margin: 5mm 5mm;/g' index.html

    - run: npm run export-pdf

    - name: Add link to html for downloading PDF
      run: |
        echo '<a href="./resume.html" target="_blank"><p>Download in PDF</p></a>' >> index.html
        echo '<embed src="./resume.pdf" type="application/pdf" width=100% height=100% />' >> resume.html

    - name: Upload resume artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume-files
        path: |
          index.html
          resume.html
          resume.pdf