name: Build and Deploy Resume

on:
  push:
    paths:
      - 'resumes/**/resume.json'
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the resume file (e.g., resumes/sample)'
        required: true
        default: 'resumes/sample'

env:
  FILE_PATH: ${{ github.event.inputs.file_path || 'resumes/sample' }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.build_step.outputs.DEST_REPO_NAME }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}

    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Make scripts executable
      run: chmod +x scripts/build-resume.sh

    - name: Build resume
      id: build_step
      run: ./scripts/build-resume.sh
      env:
        FILE_PATH: ${{ env.FILE_PATH }}

    - name: Upload resume artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume-files
        path: |
          ${{ env.FILE_PATH }}/index.html
          ${{ env.FILE_PATH }}/resume.html
          ${{ env.FILE_PATH }}/resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download resume artifacts
        uses: actions/download-artifact@v4
        with:
          name: resume-files
          path: ${{ env.FILE_PATH }}

      - name: Make scripts executable
        run: chmod +x scripts/deploy-resume.sh

      - name: Deploy resume
        env:
          FILE_PATH: ${{ env.FILE_PATH }}
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
          DEST_USERNAME: ${{ github.actor }}
          DEST_REPO_NAME: ${{ needs.build.outputs.repo_name }}-resume
          COMMIT_MESSAGE: "chore: updated resume from ${{ github.sha }}"
        run: ./scripts/deploy-resume.sh
