name: Deploy Resume

on:
  workflow_run:
    workflows: ["Build Resume"]
    types:
      - completed
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    permissions:
      actions: read

    steps:
      - name: Download resume artifacts
        uses: actions/download-artifact@v4
        with:
          name: resume-files
          run-id: ${{ github.event.workflow_run.id }}

      - name: Push to another repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone https://${{ secrets.ACTIONS_PAT }}@github.com/${{ vars.DEST_USERNAME }}/${{ vars.DEST_REPO_NAME }}.git destination_repo

          cp index.html resume.html resume.pdf destination_repo/

          cd destination_repo
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Deploy resume from ${{ github.event.workflow_run.head_sha }}"
            git push origin main
          else
            echo "No changes to deploy."
          fi